<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find locations_SearchBar__button-KIxXUfFE9V</name>
   <tag></tag>
   <elementGuidId>47c282db-7faa-4015-aab3-df2432c71835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.SearchBar__button-KIxXUfFE9V</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e352c28-7e95-4a48-9fcd-02d6b0a0c3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>742d8149-b420-42c8-8e07-bdbff88b02f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7d2b4449-cf0a-4fae-b315-a758a47c7be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBar__button-KIxXUfFE9V</value>
      <webElementGuid>96a02e04-c671-4b60-8d04-dac957d969ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[1]/header[@class=&quot;GlobalHeader-0xZ4-w1g3x&quot;]/div[@class=&quot;GlobalHeader__main-ORzg9dkzx0&quot;]/div[@class=&quot;Container-f-hqve2slU GlobalHeader__mainContainer-jduh-JKthi&quot;]/div[@class=&quot;GlobalHeader__search-oxaq0WIJpk&quot;]/form[@class=&quot;SearchBar__form-N6FZ9-N1ne notranslate&quot;]/div[@class=&quot;SearchBar__formActions-V1j1ovuVq1&quot;]/button[@class=&quot;SearchBar__button-KIxXUfFE9V&quot;]</value>
      <webElementGuid>12767a5e-9ce7-4940-a48b-94bc70d0b0c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>104f3b76-fcc2-4479-9e34-b5a17f07eb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-header']/div/header/div[2]/div/div/form/div[2]/button</value>
      <webElementGuid>bf642d21-e15a-4405-aed1-14c43ef24b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find locations'])[1]/following::button[1]</value>
      <webElementGuid>f4b8d96e-6f46-4eae-9d03-bb78baa16010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::button[1]</value>
      <webElementGuid>487db1b1-ef8d-41a5-9af8-c1ee0f305aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::button[1]</value>
      <webElementGuid>09f24dda-eb88-41ed-93d3-9305fd6e6209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse services'])[2]/preceding::button[1]</value>
      <webElementGuid>862182d2-97b9-49f5-b409-fb987af57aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>538062b2-e9d7-4819-ac22-0fc56b539e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>7de1750c-4b3a-47cf-97d3-8e9b2c6184d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
